### ISSUE TITLE
Registering for a new whatsapp password

### ISSUE THREAD

**Issue by moyamo** [stv0g/transwhat#26]
I think transwhat should allow a user to register for a new whatsapp password. The current method is not well documented. I'm not entirely sure what the registration flow should be. This is my idea:

  1. User registers with transport, filling in their phone number and leaving the password field blank
  2. Transwhat requests an sms code from whatsapp.
  3. The bot prompts the user for the sms code.
  4. The user enters the sms code.
  5. The bot then requests a password.
  6. The bot then sends the password to the user.
  7. The user must register with the transport again, but this time they fill in the password.

I don't entirely like this workflow. Suggestions would be appreciated.

**Comment by NeoBelerophon** [comment]
Can't the last step be replaced by let the bot filling in the password into the database?

**Comment by moyamo** [comment]
Yes, thanks. I hadn't thought of that. The workflow will be like this

1. User registers with transport, filling in their phone number and enters "register" in to password field.
2. The bot prompts the user for their country code.
3. The SMS code is sent
4. The bot prompts the user for the sms code
5. The password is requested.
6. The password is shown to the user and they are automatically logged in.

**Comment by fnaveira** [comment]
hi moyamo, i need help with the gateway, i have a error in  :  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_authentication.py", line 53, in onEvent
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_authentication.py", line 57, in login
    self.credentials = self._credentials or self.__getCredentials()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_authentication.py", line 37, in __getCredentials
    password = base64.b64decode(pb64)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by moyamo** [comment]
If you are trying to use this method of registering for a password, please use the develop branch. The yowsup-2 branch does not have this feature.

**Comment by fnaveira** [comment]
moyamo, i have a yousup development branch in /usr/local/lib/python2.7/dist-packages/ , but the error is the same

**Comment by moyamo** [comment]
Use the develop branch of transwhat. (Do a `git checkout develop`).

**Comment by fnaveira** [comment]
ok moyamo thanks , now the error not exist, but not send to sms code

**Comment by moyamo** [comment]
Does the bot ask you for a country code? Did you enter a country code? If so what was the bots response?

**Comment by fnaveira** [comment]
yes 34 of spain , but the error log is: 2016-01-09 22:14:45,456 INFO  NetworkPluginServer: New backend 0xfc1100 connected. Current backend count=1
2016-01-09 22:14:45,457 INFO  NetworkPluginServer: PING to 0xfc1100 (ID=)
2016-01-09 22:14:45,458 INFO  NetworkPluginServer: Associating fnaveira@xxxxx with this backend
2016-01-09 22:14:48,810 INFO  NetworkPluginServer: PING to 0xfc1100 (ID=31470)
2016-01-09 22:15:02,882 INFO  NetworkPluginServer: Backend 0xfc1100 (ID=31470) disconnected. Current backend count=0
2016-01-09 22:15:02,882 ERROR NetworkPluginServer: Backend 0xfc1100 (ID=31470) disconnected (probably crashed) with active user fnaveira@xxxxx
2016-01-09 22:15:02,882 INFO  User: fnaveira@jabber.xxxxxx: Disconnected from legacy network with error Internal Server Error, please reconnect.
2016-01-09 22:15:02,882 INFO  Component.RAW: RAW DATA OUT <message from="whatsapp.globalchat.org" to="fnaveira@xxxxxxx" type="chat"><body>Internal Server Error, please reconnect.</body><spectrumerror error="16" xmlns="http://spectrum.im/error">CONNECTION_ERROR_NETWORK_ERROR</spectrumerror></message>
2016-01-09 22:15:02,886 INFO  User: fnaveira@xxxxx: Destroying
2016-01-09 22:15:02,886 INFO  Component.RAW: RAW DATA OUT <presence from="whatsapp.xxxxx" to="fnaveira@xxxxxx" type="unavailable"/>


have you a email where can i send it these errors?

**Comment by moyamo** [comment]
moyamodehacker@gmail.com also include backend/backend.log

**Comment by moyamo** [comment]
In the password field type

    register

Do not type your jabber password

**Comment by fnaveira** [comment]
OK, OK 2016-01-09 22:46:00,540 INFO yowsup.common.http.warequest: {"status":"sent","length":6,"method":"sms","retry_after":1805} , now the bot prompts for the code country.

**Comment by moyamo** [comment]
Wait for the sms. When you get the SMS code type it into the bot window

**Comment by fnaveira** [comment]
type: existing
22:49 Logging you in :) you need help with Translation from the Spanish?

**Comment by moyamo** [comment]
For the documentation? All contributions will be appreciated :)

**Comment by fnaveira** [comment]
OK You have my support for what you need , thank you for your patience .. now to send a message to someone on my contact list like I do ?

**Comment by moyamo** [comment]
https://github.com/stv0g/transwhat/blob/7486028b35355c9d25af02c0a63d78ff5c64f529/USAGE.md#buddies Google contact import doesn't work.

**Comment by fnaveira** [comment]
I use Adium :  error do \prune

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/transwhat/bot.py", line 87, in _prune
    self.session.buddies.prune()
AttributeError: 'BuddyList' object has no attribute 'prune'

**Comment by moyamo** [comment]
Thanks, I'll file in issue. That is a bug.

**Comment by fnaveira** [comment]
the buddy list is import, but , not join the group. the buddy list is in the discover services with Whatsapp Transport , the bot send 

bot@whatsapp.globalchat.org
23:05 34xxxxxxxxxx-1375443670@whatsapp.globalchat.org Fut7torre Owner: 34xxxxxxxxxx
23:05 34xxxxxxxxxx-1451047830@whatsapp.globalchat.org Reyes 👑👑 Owner: 34xxxxxxxxxx

**Comment by fnaveira** [comment]
2016-01-09 22:49:46,851 WARNING Session: Room doesn't exist: bot. Unable to leave.

**Comment by moyamo** [comment]
File → Join Group. then put 34xxxxxxxxxx-1375443670@whatsapp.globalchat.org as address

**Comment by fnaveira** [comment]
working fine. Tkanks moyamo, We keep in contact , Best Regards ,  and sorry for my bad English

**Comment by fnaveira** [comment]
moyamo, there is a errror. a one user normal, view my groups and 
registration gives me ( the bot prompt their country code. )
