### ISSUE TITLE
d4a0593 seems to break groupchat

### ISSUE THREAD

**Issue by sezuan** [stv0g/transwhat#37]
With https://github.com/stv0g/transwhat/commit/d4a05938740c80aa3bef5e4e9a820ec8beb4e069 I get the following error when I receive a message.

    2016-01-05 13:08:07,260 ERROR transwhat: Traceback (most recent call last):
      File "/home/transwarp/transwhat/transwhat.py", line 88, in <module>
        asyncore.loop(timeout=1.0, count=10, use_poll = True)
      File "/usr/lib/python2.7/asyncore.py", line 220, in loop
        poll_fun(timeout, map)
      File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
        readwrite(obj, flags)
      File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
        obj.handle_error()
      File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
        obj.handle_read_event()
      File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
        self.handle_read()
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 86, in handle_read
        self.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 94, in receive
        self.toUpper(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
        self.__upper.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
        self.processReceived()
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
        self.toUpper(oneMessageData)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
        self.__upper.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
        self.toUpper(payload)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
        self.__upper.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
        self.toUpper(node)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
        self.__upper.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
        self.onMessage(protocolTreeNode)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 141, in onMessage
        self.toUpper(protocolTreeNode)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
        self.__upper.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 169, in receive
        s.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 105, in receive
        recv(node)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
        self.toUpper(entity)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
        self.__upper.receive(data)
      File "/home/transwarp/python/local/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 98, in receive
        self.callbacks[entityType](entity)
      File "/home/transwarp/transwhat/yowsupwrapper.py", line 655, in onMessageReceived
        entity.body
      File "/home/transwarp/transwhat/session.py", line 285, in onTextMessage
        timestamp, notify)
      File "/home/transwarp/transwhat/session.py", line 662, in sendGroupMessageToXMPP
        if defaultname != "" and group.participants[number].nick == number:
    AttributeError: 'unicode' object has no attribute 'nick'

With the previous commit I don't have this problem.

**Comment by moyamo** [comment]
Thanks for reporting! Fixed.
