### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by Myppomeu** [stv0g/transwhat#57]
Sometimes (can not find pattern) transport does not connects to server. Transport JID send me next message:
`Internal Server Error, please reconnect`
There are logs:
```
2016-04-17 02:01:30,256 INFO Session: Created: [my_number]
2016-04-17 02:01:30,257 INFO Session: ilia@xmpp attempting login
2016-04-17 02:01:39,949 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 94, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 133, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_authentication.py", line 78, in handleFailure
    raise AuthError(nodeEntity.getReason())
AuthError: not-authorized
```
Sometimes it connects, sometimes not.

Debian 8 x64, Ejabberd 16.02, Spectrum2 2.0.3, Gajim 0.16.5, latest git version of Transwhat (c66d492)

**Comment by moyamo** [comment]
It seems like many people using unofficial APIs (including me) have been blocked. See https://github.com/mgp25/Chat-API/issues/1840 https://github.com/jlguardi/yowsup/issues/75 .

**Comment by Myppomeu** [comment]
Yes, I check mobile client and I am banned.
Should I close issue?
