### ISSUE TITLE
AuthError: not-authorized

### ISSUE THREAD

**Issue by andrusstrockiy** [stv0g/transwhat#58]
Guys can anybody advice how to resolve that issue from the backend ?
<pre>
2016-04-22 18:30:00,661 INFO Session: Created: 7964705XXXX
2016-04-22 18:30:00,662 INFO Session: andruss@xmpp.mysender.ru attempting login
2016-04-22 18:30:02,240 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 94, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/opt/transwhat/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/opt/transwhat/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/opt/transwhat/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/opt/transwhat/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/opt/transwhat/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/opt/transwhat/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/opt/transwhat/yowsup/layers/axolotl/layer.py", line 133, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/opt/transwhat/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/opt/transwhat/yowsup/layers/auth/layer_authentication.py", line 78, in handleFailure
    raise AuthError(nodeEntity.getReason())
AuthError: not-authorized

</pre>

At my frontend which is xmpp (pidgin)  get the following 
(19:09:53) whatsapp.xmpp.mysender.ru: Internal Server Error, please reconnect.

And log of spectrum2.log during that session
<pre>
2016-04-22 19:09:31,158 INFO  NetworkPluginServer: New backend 0x1e4cc50 connected. Current backend count=1
2016-04-22 19:09:31,158 INFO  NetworkPluginServer: PING to 0x1e4cc50 (ID=)
2016-04-22 19:09:31,159 INFO  NetworkPluginServer: Associating andruss@xmpp.mysender.ru with this backend
2016-04-22 19:09:44,792 INFO  NetworkPluginServer: Backend 0x1e4cc50 (ID=32347) disconnected. Current backend count=0
2016-04-22 19:09:44,792 ERROR NetworkPluginServer: Backend 0x1e4cc50 (ID=32347) disconnected (probably crashed) with active user andruss@xmpp.mysender.ru
2016-04-22 19:09:44,792 INFO  User: andruss@xmpp.mysender.ru: Disconnecting from legacy network Internal Server Error, please reconnect., trying to reconnect automatically.
2016-04-22 19:09:44,793 INFO  NetworkPluginServer: Starting new backend /opt/transwhat/transwhat.py --host localhost --port 32710 --service.backend_id=2 "-j" "whatsapp.xmpp.mysender.ru" "/etc/spectrum2/transports/whatsapp.cfg" 
2016-04-22 19:09:44,794 INFO  NetworkPluginServer: There is no backend to handle user andruss@xmpp.mysender.ru. Adding him to queue.
2016-04-22 19:09:45,812 INFO  NetworkPluginServer: New backend 0x1e4cc50 connected. Current backend count=1
2016-04-22 19:09:45,812 INFO  NetworkPluginServer: PING to 0x1e4cc50 (ID=)
2016-04-22 19:09:45,814 INFO  NetworkPluginServer: Associating andruss@xmpp.mysender.ru with this backend
2016-04-22 19:09:50,711 INFO  NetworkPluginServer: Sending PING to backends
2016-04-22 19:09:50,711 INFO  NetworkPluginServer: PING to 0x1e4cc50 (ID=32348)
2016-04-22 19:09:55,758 INFO  NetworkPluginServer: Backend 0x1e4cc50 (ID=32348) disconnected. Current backend count=0
2016-04-22 19:09:55,758 ERROR NetworkPluginServer: Backend 0x1e4cc50 (ID=32348) disconnected (probably crashed) with active user andruss@xmpp.mysender.ru
2016-04-22 19:09:55,758 INFO  User: andruss@xmpp.mysender.ru: Disconnected from legacy network with error Internal Server Error, please reconnect.
2016-04-22 19:09:55,759 INFO  Component.RAW: RAW DATA OUT <message from="whatsapp.xmpp.mysender.ru" to="andruss@xmpp.mysender.ru" type="chat"><body>Internal Server Error, please reconnect.</body><spectrumerror error="16" xmlns="http://spectrum.im/error">CONNECTION_ERROR_NETWORK_ERROR</spectrumerror></message>
2016-04-22 19:09:55,881 INFO  UserManager: andruss@xmpp.mysender.ru: Disconnecting user
2016-04-22 19:09:55,881 INFO  User: andruss@xmpp.mysender.ru: Destroying
2016-04-22 19:09:55,881 INFO  Component.RAW: RAW DATA OUT <presence from="whatsapp.xmpp.mysender.ru" to="andruss@xmpp.mysender.ru" type="unavailable"/>
</pre>

Any ideas if spectrumerror error="16"  and CONNECTION_ERROR_NETWORK_ERROR ?

**Comment by stv0g** [comment]
Please see #57
