### ISSUE TITLE
NameError: global name 'YowStackBuilder' is not defined

### ISSUE THREAD

**Issue by datenklause** [stv0g/transwhat#62]
Tried both development and yowsup-2 branches. Component registers with prosody, is shown there in xmpp service discovery, I can register a whatsapp with it with Pidgin, but then it hangs.

backend.log :

2016-10-09 21:38:13,532 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 80, in handleTransportData
    plugin.handleDataRead(data)
  File "/opt/transwhat/Spectrum2/backend.py", line 418, in handleDataRead
    self.handleLoginPayload(wrapper.payload)
  File "/opt/transwhat/Spectrum2/backend.py", line 259, in handleLoginPayload
    self.handleLoginRequest(payload.user, payload.legacyName, payload.password, payload.extraFields)
  File "/opt/transwhat/whatsappbackend.py", line 60, in handleLoginRequest
    self.sessions[user] = Session(self, user, legacyName, extra)
  File "/opt/transwhat/session.py", line 60, in **init**
    super(Session, self).**init**()
  File "/opt/transwhat/yowsupwrapper.py", line 89, in **init**
    stackBuilder = YowStackBuilder()
NameError: global name 'YowStackBuilder' is not defined

spectrum2.log

2016-10-09 21:37:44,807 INFO  User: sirko@datenklause.de: Changing legacy network presence to 0
2016-10-09 21:37:44,808 INFO  UserManager: PRESENCE2 whatsapp.datenklause.de
2016-10-09 21:37:44,810 INFO  User: sirko@datenklause.de/08168e94-bf4c-465c-a0fa-32e007eab438: got disco#info
2016-10-09 21:37:44,811 INFO  Component.RAW: RAW DATA OUT <iq from="whatsapp.datenklause.de" id="65fe1ffe-27fc-411b-9191-16601d7dc7ae" to="sirko@datenklause.de/08168e94-bf4c-465c-a0fa-32e007eab438" type="get"><query xmlns="http://jabber.org/protocol/disco#info"/></iq>
2016-10-09 21:37:44,812 INFO  User: PRESENCE sirko@datenklause.de/08168e94-bf4c-465c-a0fa-32e007eab438 whatsapp.datenklause.de
2016-10-09 21:37:44,814 INFO  Component.RAW: RAW DATA OUT <presence from="whatsapp.datenklause.de" to="sirko@datenklause.de/08168e94-bf4c-465c-a0fa-32e007eab438" type="unavailable"><status>Connecting</status></presence>
2016-10-09 21:37:44,815 INFO  User: sirko@datenklause.de: Changing legacy network presence to 2
2016-10-09 21:37:44,816 INFO  UserManager: PRESENCE2 whatsapp.datenklause.de
2016-10-09 21:37:44,817 INFO  Component.RAW: RAW DATA IN <iq id='ac87ed10-3cf8-4363-88d8-6df384e5a082' type='result' to='whatsapp.datenklause.de' from='sirko@datenklause.de'><query xmlns='jabber:iq:roster'><item jid='whatsapp.datenklause.de' subscription='both'><group>Buddies</group></item></query></iq>
2016-10-09 21:37:44,818 INFO  XMPPRosterManager: sirko@datenklause.de: This server supports remote roster protoXEP
2016-10-09 21:37:45,025 INFO  Component.RAW: RAW DATA IN <iq type='result' to='whatsapp.datenklause.de' from='sirko@datenklause.de/08168e94-bf4c-465c-a0fa-32e007eab438' id='65fe1ffe-27fc-411b-9191-16601d7dc7ae'><query xmlns='http://jabber.org/protocol/disco#info'><identity type='pc' name='Pidgin' category='client'/><feature var='jabber:iq:last'/><feature var='jabber:iq:oob'/><feature var='urn:xmpp:time'/><feature var='jabber:iq:version'/><feature var='jabber:x:conference'/><feature var='http://jabber.org/protocol/bytestreams'/><feature var='http://jabber.org/protocol/caps'/><feature var='http://jabber.org/protocol/chatstates'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='http://jabber.org/protocol/muc'/><feature var='http://jabber.org/protocol/muc#user'/><feature var='http://jabber.org/protocol/si'/><feature var='http://jabber.org/protocol/si/profile/file-transfer'/><feature var='http://jabber.org/protocol/xhtml-im'/><feature var='urn:xmpp:ping'/><feature var='urn:xmpp:attention:0'/><feature var='urn:xmpp:bob'/><feature var='urn:xmpp:jingle:1'/><feature var='http://www.google.com/xmpp/protocol/session'/><feature var='http://www.google.com/xmpp/protocol/voice/v1'/><feature var='http://www.google.com/xmpp/protocol/video/v1'/><feature var='http://www.google.com/xmpp/protocol/camera/v1'/><feature var='urn:xmpp:jingle:apps:rtp:1'/><feature var='urn:xmpp:jingle:apps:rtp:audio'/><feature var='urn:xmpp:jingle:apps:rtp:video'/><feature var='urn:xmpp:jingle:transports:raw-udp:1'/><feature var='urn:xmpp:jingle:transports:ice-udp:1'/><feature var='urn:xmpp:avatar:metadata'/><feature var='urn:xmpp:avatar:data'/><feature var='urn:xmpp:avatar:metadata+notify'/><feature var='http://jabber.org/protocol/mood'/><feature var='http://jabber.org/protocol/mood+notify'/><feature var='http://jabber.org/protocol/tune'/><feature var='http://jabber.org/protocol/tune+notify'/><feature var='http://jabber.org/protocol/nick'/><feature var='http://jabber.org/protocol/nick+notify'/><feature var='http://jabber.org/protocol/ibb'/></query></iq>
2016-10-09 21:37:45,030 INFO  User: sirko@datenklause.de/08168e94-bf4c-465c-a0fa-32e007eab438: got disco#info
2016-10-09 21:37:50,246 INFO  NetworkPluginServer: Sending PING to backends
2016-10-09 21:37:50,247 INFO  NetworkPluginServer: PING to 0x18fe890 (ID=10955)
2016-10-09 21:38:10,248 INFO  NetworkPluginServer: Sending PING to backends
2016-10-09 21:38:10,248 INFO  NetworkPluginServer: Disconnecting backend 0x18fe890 (ID=10955). PING response not received.
2016-10-09 21:38:10,249 INFO  NetworkPluginServer: Backend 0x18fe890 (ID=10955) disconnected. Current backend count=0
2016-10-09 21:38:10,249 ERROR NetworkPluginServer: Backend 0x18fe890 (ID=10955) disconnected (probably crashed) with active user sirko@datenklause.de
2016-10-09 21:38:10,249 INFO  User: sirko@datenklause.de: Disconnecting from legacy network Internal Server Error, please reconnect., trying to reconnect automatically.
2016-10-09 21:38:10,252 INFO  NetworkPluginServer: Starting new backend /opt/transwhat/transwhat.py --host 127.0.0.1 --port 35293 --service.backend_id=2 "-j" "whatsapp.datenklause.de" "/etc/spectrum2/transports/whatsapp.cfg" 
2016-10-09 21:38:10,256 INFO  NetworkPluginServer: There is no backend to handle user sirko@datenklause.de. Adding him to queue.
2016-10-09 21:38:13,490 INFO  NetworkPluginServer: New backend 0x18fe890 connected. Current backend count=1
2016-10-09 21:38:13,492 INFO  NetworkPluginServer: PING to 0x18fe890 (ID=)
2016-10-09 21:38:13,500 INFO  NetworkPluginServer: Associating sirko@datenklause.de with this backend
2016-10-09 21:38:26,477 INFO  UserManager: sirko@datenklause.de: Disconnecting user
2016-10-09 21:38:26,479 INFO  User: sirko@datenklause.de: Destroying
2016-10-09 21:38:26,479 INFO  Component.RAW: RAW DATA OUT <presence from="whatsapp.datenklause.de" to="sirko@datenklause.de" type="unavailable"/>
2016-10-09 21:38:26,482 INFO  MySQLBackend: Disconnecting
2016-10-09 21:38:26,489 INFO  NetworkPluginServer: Stopping backend 0x18fe890
2016-10-09 21:38:26,500 INFO  cerr: Warning: Pending events in SimpleEventLoop at destruction tim

Any ideas?

**Comment by sk1ppa** [comment]
Please edit "yowsupwrapper.py" in your transwhat directory, to include:

`from yowsup.stacks import YowStack
from yowsup.stacks import YowStackBuilder
from yowsup.common import YowConstants
`

The second line will helps you.

Regards,
Simon
