### ISSUE TITLE
Not possible to receive images

### ISSUE THREAD

**Issue by mw80** [stv0g/transwhat#72]
When sending an image from whatsapp to transwhat, I am just receiving a link in my xmpp client: https://mmi644.whatsapp.net/d/.... .enc Is there anything in my configuration wrong?

**Comment by vitalyster** [comment]
What do you want to see? client may download your link automatically and display in chat, no need anything else from transport side

**Comment by mw80** [comment]
The problem is the file is encrypted.

**Comment by mw80** [comment]
I would expect a similar approach as for sending images. download the whatsapp image, decrypt the image, upload the decrypted image to an http upload component

**Comment by mw80** [comment]
Maybe this is the right approach?
-> DownloadableMediaMessageProtocolEntity.getMediaContent()
https://github.com/tgalal/yowsup/issues/1811

**Comment by mw80** [comment]
I've done some debugging. The issue seems to be related to my yowsup version. My version has no DownloadableMediaMessageProtocolEntity.getExtension method. Which yowsup are you using?

**Comment by stv0g** [comment]
I used the latest `master` branch.

I will close this issue. Please re-open if it is not only because of your older yowsup version

**Comment by mw80** [comment]
I am using latest yowsup https://github.com/tgalal/yowsup. There is no getExtension method.

**Comment by mw80** [comment]
2017-03-02 00:41:17,527 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transWhat/transwhat.py", line 107, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 200, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 238, in handleImageMessage
    self.toUpper(messageNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/layer.py", line 42, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/opt/transwhat/transWhat/yowsupwrapper.py", line 857, in onMessageReceived
    self.caller.onImage(entity)
  File "/opt/transwhat/transWhat/session.py", line 314, in onImage
    ipath = "/" + str(image.timestamp)  + image.getExtension()
AttributeError: 'ImageDownloadableMediaMessageProtocolEntity' object has no attribute 'getExtension'

**Comment by stv0g** [comment]
Should b fixed by #75

**Comment by mw80** [comment]
Hm, getExtension is still used:
ipath = "/" + str(media.timestamp)  + media.getExtension() 

I searched the repository https://github.com/tgalal/yowsup. But I have no idea where this method is defined :(

**Comment by Nicos-git** [comment]
Hi @mw80,

you could use jlguardis master https://github.com/jlguardi/yowsup or parts of it.
