### ISSUE TITLE
Permission denied: Various errors

### ISSUE THREAD

**Issue by o---** [stv0g/transwhat#89]
When I execute **spectrum2_manager start whatsapp**, I get lots of errors, but what I am taking out of it some werid permission errors. _What permissions should I be setting_? Thanks

Traceback (most recent call last):
  File "/usr/bin/transwhat", line 9, in <module>
    load_entry_point('transwhat==0.2.2', 'console_scripts', 'transwhat')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/transWhat/transwhat.py", line 67, in <module>
    level = logging.DEBUG if args.debug else logging.INFO
  File "/usr/lib64/python2.7/logging/__init__.py", line 1529, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: u'/var/log/spectrum2/whatsapp.domain.com/backends/backend.log'

**From spectrum2 log:**
2018-02-25 11:37:41,579 INFO  NetworkPluginServer: Tried to spawn first backend with pid 1808
2018-02-25 11:37:41,579 INFO  NetworkPluginServer: Backend should now connect to Spectrum2 instance. Spectrum2 won't accept any connection before backend connects
2018-02-25 11:37:42,579 ERROR NetworkPluginServer: Backend can not be started, exit_code=1, possible error: **Operation not permitted**
2018-02-25 11:37:42,580 ERROR NetworkPluginServer: Check backend log for more details
2018-02-25 11:37:42,580 INFO  NetworkPluginServer: Starting new backend /usr/bin/transwhat --host localhost --port 33388 --service.backend_id=1 "-j" "whatsapp.domain.com" "/etc/spectrum2/trans
ports/whatsapp.cfg"

**after CHMOD 666** 

Traceback (most recent call last):
  File "/usr/bin/transwhat.py", line 5, in <module>
    pkg_resources.run_script('transwhat==0.2.2', 'transwhat.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/EGG-INFO/scripts/transwhat.py", line 100, in <module>
    ('muc', 'true'),
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/Spectrum2/backend.py", line 269, in handleBackendConfig
    self.send(message)
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/Spectrum2/backend.py", line 486, in send
    header = struct.pack('!I',len(data))
TypeError: Struct() argument 1 must be string, not unicode

**After I replaced /usr/bin/transwhat.py**
Traceback (most recent call last):
  File "/usr/bin/transwhat.py", line 100, in <module>
    ('muc', 'true'),
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/Spectrum2/backend.py", line 269, in handleBackendConfig
    self.send(message)
  File "/usr/lib/python2.7/site-packages/transwhat-0.2.2-py2.7.egg/Spectrum2/backend.py", line 486, in send
    header = struct.pack('!I',len(data))
TypeError: Struct() argument 1 must be string, not unicode

**Comment by stv0g** [comment]
The permission denied errors are due to a wrong installation and related to Spectrum.

For the other issue, please create a more specific bug report.
